// Canonical free-form tag values used in questions/flashcards/topics JSON.
//
// Why this module exists: question JSON cannot import TypeScript, so this file
// is the documented source of truth. Author every question's `tags` array using
// values from TAGS to keep the vocabulary consistent and typo-free across files.
//
// Note: weakSpotTags is a separate, closed enum in ./weak-spots.ts (and is what
// the Weak-Spot dashboard rolls up). The TAGS below are for the broader
// free-form `tags` field on questions/flashcards/topics.

export const TAGS = {
  // ── Domain 1: Operating Systems ─────────────────────────

  // 1.1 OS types & file systems
  WORKSTATION_OS: 'workstation-os',
  MOBILE_OS: 'mobile-os',
  WINDOWS: 'windows',
  MACOS: 'macos',
  LINUX: 'linux',
  CHROME_OS: 'chrome-os',
  IOS: 'ios',
  IPADOS: 'ipados',
  ANDROID: 'android',
  FILESYSTEMS: 'filesystems',
  NTFS: 'ntfs',
  FAT32: 'fat32',
  EXFAT: 'exfat',
  APFS: 'apfs',
  EXT4: 'ext4',
  XFS: 'xfs',
  REFS: 'refs',
  EOL: 'eol',
  COMPATIBILITY: 'compatibility',
  WEB_APPS: 'web-apps',

  // 1.2 installs & boot
  BOOT_METHODS: 'boot-methods',
  USB_BOOT: 'usb-boot',
  PXE: 'pxe',
  CLEAN_INSTALL: 'clean-install',
  IN_PLACE_UPGRADE: 'in-place-upgrade',
  REPAIR_INSTALL: 'repair-install',
  IMAGE_DEPLOYMENT: 'image-deployment',
  PARTITIONING: 'partitioning',
  MBR: 'mbr',
  GPT: 'gpt',
  QUICK_FORMAT: 'quick-format',
  FULL_FORMAT: 'full-format',
  TPM: 'tpm',
  SECURE_BOOT: 'secure-boot',
  UEFI: 'uefi',

  // 1.3 Windows editions
  WINDOWS_EDITIONS: 'windows-editions',
  HOME: 'home',
  PRO: 'pro',
  PRO_WORKSTATIONS: 'pro-workstations',
  ENTERPRISE: 'enterprise',
  WORKGROUP: 'workgroup',
  DOMAIN: 'domain',
  BITLOCKER: 'bitlocker',
  EFS: 'efs',
  GROUP_POLICY: 'group-policy',
  HYPERV: 'hyper-v',
  RDP: 'rdp',
  GPEDIT: 'gpedit',
  GPMC: 'gpmc',

  // 1.4 Windows tools
  TASK_MANAGER: 'task-manager',
  MSINFO32: 'msinfo32',
  RESMON: 'resmon',
  MSCONFIG: 'msconfig',
  MMC: 'mmc',
  EVENT_VIEWER: 'event-viewer',
  DEVICE_MANAGER: 'device-manager',
  DISK_MGMT: 'disk-management',
  PERFMON: 'perfmon',
  LUSRMGR: 'lusrmgr',
  DISK_CLEANUP: 'disk-cleanup',
  DEFRAG: 'defrag',
  REGEDIT: 'regedit',

  // 1.5 CLI
  CLI: 'cli',
  CHKDSK: 'chkdsk',
  DISKPART: 'diskpart',
  ROBOCOPY: 'robocopy',
  SFC: 'sfc',
  IPCONFIG: 'ipconfig',
  PING: 'ping',
  NETSTAT: 'netstat',
  NSLOOKUP: 'nslookup',
  TRACERT: 'tracert',
  PATHPING: 'pathping',
  GPUPDATE: 'gpupdate',
  GPRESULT: 'gpresult',
  HOSTNAME: 'hostname',
  WINVER: 'winver',
  WHOAMI: 'whoami',
  ELEVATED_PROMPT: 'elevated-prompt',

  // 1.6 Settings / Control Panel
  CONTROL_PANEL: 'control-panel',
  WINDOWS_SETTINGS: 'windows-settings',
  INTERNET_OPTIONS: 'internet-options',
  FILE_EXPLORER_OPTIONS: 'file-explorer-options',
  POWER_OPTIONS: 'power-options',
  SLEEP: 'sleep',
  HIBERNATE: 'hibernate',
  FAST_STARTUP: 'fast-startup',

  // 1.7 Windows networking
  FIREWALL: 'firewall',
  DHCP: 'dhcp',
  STATIC_IP: 'static-ip',
  APIPA: 'apipa',
  VPN: 'vpn',
  PROXY: 'proxy',
  UNC: 'unc',
  MAPPED_DRIVE: 'mapped-drive',
  METERED: 'metered',
  SSID: 'ssid',

  // 1.8 macOS
  TIME_MACHINE: 'time-machine',
  MISSION_CONTROL: 'mission-control',
  SPOTLIGHT: 'spotlight',
  KEYCHAIN: 'keychain',
  ICLOUD: 'icloud',
  FILE_VAULT: 'file-vault',
  DISK_UTILITY: 'disk-utility',
  FORCE_QUIT: 'force-quit',
  DMG: 'dmg',
  PKG: 'pkg',
  APP_BUNDLE: 'app-bundle',
  CONTINUITY: 'continuity',
  RSR: 'rsr',

  // 1.9 Linux
  KERNEL: 'kernel',
  SYSTEMD: 'systemd',
  ROOT: 'root',
  SUDO: 'sudo',
  SU: 'su',
  CHMOD: 'chmod',
  CHOWN: 'chown',
  APT: 'apt',
  DNF: 'dnf',
  IP_CMD: 'ip-cmd',
  DIG: 'dig',
  PS: 'ps',
  TOP: 'top',
  DF: 'df',
  DU: 'du',
  CAT: 'cat',
  NANO: 'nano',
  MAN: 'man',
  ETC_PASSWD: 'etc-passwd',
  ETC_SHADOW: 'etc-shadow',
  ETC_HOSTS: 'etc-hosts',
  ETC_RESOLV: 'etc-resolv',

  // 1.10 App install
  APP_REQUIREMENTS: 'app-requirements',
  ARCH_32_64: 'arch-32-64',
  HARDWARE_TOKEN: 'hardware-token',
  ISO: 'iso',
  SANDBOX: 'sandbox',
  DEDICATED_GRAPHICS: 'dedicated-graphics',
  INTEGRATED_GRAPHICS: 'integrated-graphics',

  // 1.11 Cloud
  CLOUD: 'cloud',
  CLOUD_STORAGE_SYNC: 'cloud-storage-sync',
  IDENTITY_SYNC: 'identity-sync',
  LICENSE_ASSIGNMENT: 'license-assignment',
  SCALABILITY: 'scalability',
  HIGH_AVAILABILITY: 'high-availability',

  // ── Domain 2: Security ──────────────────────────────────
  IAM: 'iam',
  SSO: 'sso',
  SAML: 'saml',
  LEAST_PRIVILEGE: 'least-privilege',
  PAM: 'pam',
  ZERO_TRUST: 'zero-trust',
  JUST_IN_TIME: 'just-in-time',
  DLP: 'dlp',
  MDM: 'mdm',
  MFA: 'mfa',
  TOTP: 'totp',
  PHYSICAL_SECURITY: 'physical-security',
  VESTIBULE: 'vestibule',
  BIOMETRICS: 'biometrics',
  UAC: 'uac',
  WINDOWS_HELLO: 'windows-hello',
  NTFS_PERMISSIONS: 'ntfs-permissions',
  SHARE_PERMISSIONS: 'share-permissions',
  ACTIVE_DIRECTORY: 'active-directory',
  OU: 'ou',
  RADIUS: 'radius',
  TACACS: 'tacacs',
  KERBEROS: 'kerberos',
  WEP: 'wep',
  WPA: 'wpa',
  WPA2: 'wpa2',
  WPA3: 'wpa3',
  TKIP: 'tkip',
  AES: 'aes',
  PSK: 'psk',
  DOT1X: '802.1x',
  MALWARE: 'malware',
  TROJAN: 'trojan',
  VIRUS: 'virus',
  ROOTKIT: 'rootkit',
  SPYWARE: 'spyware',
  KEYLOGGER: 'keylogger',
  RANSOMWARE: 'ransomware',
  BOOT_SECTOR_VIRUS: 'boot-sector-virus',
  CRYPTOMINER: 'cryptominer',
  STALKERWARE: 'stalkerware',
  FILELESS: 'fileless',
  ADWARE: 'adware',
  EDR: 'edr',
  MDR: 'mdr',
  XDR: 'xdr',
  WINRE: 'winre',
  WINPE: 'winpe',
  PHISHING: 'phishing',
  VISHING: 'vishing',
  SMISHING: 'smishing',
  QUISHING: 'quishing',
  SPEAR_PHISHING: 'spear-phishing',
  WHALING: 'whaling',
  SHOULDER_SURFING: 'shoulder-surfing',
  TAILGATING: 'tailgating',
  IMPERSONATION: 'impersonation',
  DUMPSTER_DIVING: 'dumpster-diving',
  BEC: 'bec',
  ONPATH: 'onpath',
  EVIL_TWIN: 'evil-twin',
  DOS: 'dos',
  DDOS: 'ddos',
  BRUTE_FORCE: 'brute-force',
  DICTIONARY: 'dictionary',
  SQL_INJECTION: 'sql-injection',
  XSS: 'xss',
  ZERO_DAY: 'zero-day',
  SUPPLY_CHAIN: 'supply-chain',
  INSIDER_THREAT: 'insider-threat',
  MALWARE_REMOVAL_10_STEP: 'malware-removal-10-step',
  SAFE_MODE: 'safe-mode',
  SYSTEM_RESTORE: 'system-restore',
  HARDENING: 'hardening',
  PASSWORD_POLICY: 'password-policy',
  BIOS_PASSWORD: 'bios-password',
  SCREEN_LOCK: 'screen-lock',
  PASSWORD_MANAGER: 'password-manager',
  PII: 'pii',
  MOBILE_SECURITY: 'mobile-security',
  REMOTE_WIPE: 'remote-wipe',
  PATCH_MANAGEMENT: 'patch-management',
  BYOD: 'byod',
  DATA_DESTRUCTION: 'data-destruction',
  DEGAUSSING: 'degaussing',
  DBAN: 'dban',
  CERTIFICATE_OF_DESTRUCTION: 'certificate-of-destruction',
  SOHO_SECURITY: 'soho-security',
  UPNP: 'upnp',
  DMZ: 'dmz',
  GUEST_NETWORK: 'guest-network',
  PORT_FORWARDING: 'port-forwarding',
  BROWSER_SECURITY: 'browser-security',
  HASHING: 'hashing',
  BROWSER_EXTENSIONS: 'browser-extensions',
  CERTIFICATE_WARNING: 'certificate-warning',
  POPUP_BLOCKER: 'popup-blocker',
  PRIVATE_BROWSING: 'private-browsing',
  SECURE_DNS: 'secure-dns',

  // ── Domain 3: Troubleshooting ───────────────────────────
  TROUBLESHOOTING: 'troubleshooting',
  BSOD: 'bsod',
  STARTUP_REPAIR: 'startup-repair',
  BOOTREC: 'bootrec',
  RELIABILITY_MONITOR: 'reliability-monitor',
  VIRTUAL_MEMORY: 'virtual-memory',
  USB_CONTROLLER: 'usb-controller',
  TIME_DRIFT: 'time-drift',
  MOBILE_TROUBLESHOOTING: 'mobile-troubleshooting',
  FORCE_STOP: 'force-stop',
  RANDOM_REBOOTS: 'random-reboots',
  BATTERY_LIFE: 'battery-life',
  ROTATION_LOCK: 'rotation-lock',
  SIDELOADING: 'sideloading',
  APP_SPOOFING: 'app-spoofing',
  ROOTING: 'rooting',
  JAILBREAKING: 'jailbreaking',
  SCAREWARE: 'scareware',
  BROWSER_HIJACKER: 'browser-hijacker',
  REDIRECTION: 'redirection',
  FACTORY_RESET: 'factory-reset',

  // ── Domain 4: Operational Procedures ────────────────────
  DOCUMENTATION: 'documentation',
  CMDB: 'cmdb',
  ASSET_TAGS: 'asset-tags',
  PROCUREMENT: 'procurement',
  TICKETING: 'ticketing',
  ESCALATION: 'escalation',
  SOP: 'sop',
  INCIDENT_REPORT: 'incident-report',
  ONBOARDING: 'onboarding',
  OFFBOARDING: 'offboarding',
  SLA: 'sla',
  CHANGE_MANAGEMENT: 'change-management',
  STANDARD_CHANGE: 'standard-change',
  NORMAL_CHANGE: 'normal-change',
  EMERGENCY_CHANGE: 'emergency-change',
  MAINTENANCE_WINDOW: 'maintenance-window',
  CHANGE_FREEZE: 'change-freeze',
  ROLLBACK: 'rollback',
  CCB: 'ccb',
  BACKUP: 'backup',
  FULL_BACKUP: 'full-backup',
  DIFFERENTIAL_BACKUP: 'differential-backup',
  INCREMENTAL_BACKUP: 'incremental-backup',
  SYNTHETIC_FULL: 'synthetic-full',
  GFS: 'gfs',
  THREE_TWO_ONE: '3-2-1',
  SAFETY: 'safety',
  ESD: 'esd',
  ESD_STRAP: 'esd-strap',
  CAPACITOR: 'capacitor',
  CABLE_MANAGEMENT: 'cable-management',
  FIRE_SUPPRESSION: 'fire-suppression',
  MSDS: 'msds',
  HUMIDITY: 'humidity',
  UPS: 'ups',
  SURGE_SUPPRESSOR: 'surge-suppressor',
  INCIDENT_RESPONSE: 'incident-response',
  CHAIN_OF_CUSTODY: 'chain-of-custody',
  ORDER_OF_VOLATILITY: 'order-of-volatility',
  EULA: 'eula',
  PER_SEAT_LICENSE: 'per-seat-license',
  CONCURRENT_LICENSE: 'concurrent-license',
  FOSS: 'foss',
  NDA: 'nda',
  PHI: 'phi',
  HIPAA: 'hipaa',
  PCI_DSS: 'pci-dss',
  AUP: 'aup',
  PROFESSIONALISM: 'professionalism',
  COMMUNICATION: 'communication',
  SCRIPTING: 'scripting',
  BAT: 'bat',
  PS1: 'ps1',
  VBS: 'vbs',
  SH: 'sh',
  JS: 'js',
  PY: 'py',
  REMOTE_ACCESS: 'remote-access',
  RDP_3389: 'rdp-3389',
  VNC: 'vnc',
  SPICE: 'spice',
  SSH_22: 'ssh-22',
  TELNET: 'telnet',
  RMM: 'rmm',
  WINRM: 'winrm',
  AI: 'ai',
  DEEPFAKE: 'deepfake',
  AI_BIAS: 'ai-bias',
  AI_HALLUCINATION: 'ai-hallucination',
  PUBLIC_AI: 'public-ai',
  PRIVATE_AI: 'private-ai',
} as const satisfies Record<string, string>;

export type Tag = (typeof TAGS)[keyof typeof TAGS];

export const ALL_TAGS: readonly Tag[] = Object.values(TAGS);

export function isTag(value: string): value is Tag {
  return (ALL_TAGS as readonly string[]).includes(value);
}
