// Merge per-chunk JSON files from data/gen/ into data/questions.js.
// Orders questions by domain (D1..D5) then by family registry order, then as generated.
// Assigns sequential ids q001..qNNN.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FAMILIES } from "../data/families.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const genDir = join(__dirname, "..", "data", "gen");
const outFile = join(__dirname, "..", "data", "questions.js");

const familyOrder = new Map(FAMILIES.map((f, i) => [f.key, i]));
const domainOrder = { D1: 0, D2: 1, D3: 2, D4: 3, D5: 4 };

const files = readdirSync(genDir).filter((f) => f.endsWith(".json")).sort();
let all = [];
for (const f of files) {
  const raw = readFileSync(join(genDir, f), "utf8");
  let arr;
  try {
    arr = JSON.parse(raw);
  } catch (e) {
    console.error(`FAILED to parse ${f}: ${e.message}`);
    process.exit(1);
  }
  if (!Array.isArray(arr)) {
    console.error(`${f} is not a JSON array`);
    process.exit(1);
  }
  console.log(`${f}: ${arr.length} questions`);
  all = all.concat(arr);
}

// stable sort by domain, then family registry order, then original order
all.forEach((q, i) => (q._i = i));
all.sort((a, b) => {
  const d = (domainOrder[a.domain] ?? 99) - (domainOrder[b.domain] ?? 99);
  if (d) return d;
  const fa = familyOrder.has(a.family) ? familyOrder.get(a.family) : 999;
  const fb = familyOrder.has(b.family) ? familyOrder.get(b.family) : 999;
  if (fa !== fb) return fa - fb;
  return a._i - b._i;
});

const questions = all.map((q, i) => ({
  id: "q" + String(i + 1).padStart(3, "0"),
  domain: q.domain,
  family: q.family,
  question: q.question,
  options: q.options,
  correctIndex: q.correctIndex,
  explanation: q.explanation,
}));

const header =
  "// AUTO-GENERATED by scripts/merge.mjs. CompTIA Security+ SY0-701 twin-term drill bank.\n" +
  "// Do not edit by hand; edit the chunk sources in data/gen/ and re-run merge.\n";
const body =
  "export const QUESTIONS = [\n" +
  questions
    .map((q) => "  " + JSON.stringify(q))
    .join(",\n") +
  "\n];\n";

writeFileSync(outFile, header + body);
console.log(`\nWrote ${questions.length} questions to data/questions.js`);
